### PR TITLE
added abstraction for sky130_fd_io__signal_5_sym_hv_local_5term

### PR DESCRIPTION
**Pull request by ahmednofal**

### CODE REVIEW

**Comment by ahmednofal** [comment]
@jeffdi

**Review by RTimothyEdwards — CHANGES_REQUESTED** [review]
I don't want to leave messages like "No signal...5term was found".  This will just confuse users.  Better to say that it was found when it is found and not generate any output otherwise, since most users have no idea what the cell is or does.  Also, you are generating diagnostic output about the SRAM in magic_drc_check.tcl but generating output about the ESD FET in run_drc_magic.sh.  Be consistent and generate all diagnostic messages from the same script.

**Comment by ahmednofal** [comment]
@RTimothyEdwards Can you please recheck this, it has been amended

**Review by RTimothyEdwards — APPROVED** [review]
Looks good to me.

**Pull request merged**
